CFLAGS = -std=c++17 -Wall -g
CC = g++
STANDARD_GREEDY_SOURCES = activity_selection.cpp egyptian_fraction.cpp job_sequencing.cpp job_sequencing_loss_minimization.cpp huffman_encoding.cpp huffman_encoding_sortedInput.cpp brackets_matching.cpp

all:
	$(CC) $(CFLAGS) main.cpp $(STANDARD_GREEDY_SOURCES)  -o standard_greedy.bin
	
clean:
	rm *.bin
