CFLAGS = -std=c++17 -Wall -g
CC = g++
STANDARD_GREEDY_SOURCES = activity_selection.cpp egyptian_fraction.cpp job_sequencing.cpp

all:
	$(CC) $(CFLAGS) main.cpp $(STANDARD_GREEDY_SOURCES)  -o standard_greedy.bin
	
clean:
	rm *.bin
